-- AlterTable
ALTER TABLE `Ship` ADD COLUMN `ownerId` INTEGER NOT NULL DEFAULT 1;

-- AddForeignKey
ALTER TABLE `Ship` ADD CONSTRAINT `Ship_ownerId_fkey` FOREIGN KEY (`ownerId`) REFERENCES `User`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
